= About
This repo tracks my user-level dot-files and explicitly installed system
packages.

`chezmoi`, pronounced "shay-moi", is a dot-file manager. The manager has many
features which may be useful in the future. For example, the templating feature
can be used to track common configuration between multiple diverging 
configurations. See the 
https://www.chezmoi.io/user-guide/manage-machine-to-machine-differences/[docs].

Explicitly installed packages are tracked so commits will contain all 
information for known, good states. Its unlikely that all packages listed for a
particular commit will be installed on a new machine because there will likely
be some unneeded packages. However, the reference is valuable.

The explicitly installed packages are automatically tracked for each commit
through a pre-commit hook. Currently, `pacman` and `yay` packages are parsed
and `native` and `foreign` package lists are created, respectively. The scripts
also parse an ignore file. To ensure tracking on a per-commit basis, a git hook
is used. The https://pre-commit.com/[pre-commit] framework manages the git
hook.

== Installation
. Install https://www.chezmoi.io/[`chezmoi`]
.. Run `chezmoi init --apply silaswaxter`
. Install `pre-commit`
.. Install `conda` onto the system using the
   https://docs.conda.io/en/main/miniconda.html[miniconda installer].
.. Create the conda environment by running
   `conda-env create -f ./conda-environment.yml`

== Configuration decisions
The following contain information pertaining to the decisions and non-intuititve
portions of my configuration.

=== Display scripts
I've found its easiest to setup displays using a GUI, for example, `arandr`, 
rather than direct `xrandr` commands. After the display configuration is
correct, it can be exported as a script and saved to `.screenlayout/`. 
`.screenlayou/auto_display.sh` finds which outputs are connected and calls the 
corresponding display script that was generated by the GUI. This script allows
other programs, for example `i3wm`, to update the display configuration in a
standard way. The script will take care of doing what is 'right'. The specific
mappings and generated scripts will need to be modified on a **per-machine
basis**. 

=== Pacwall
`pacwall` generates a kick-ass wallpaper that is an annotated dependency graph 
of the currently installed system packages. It sets the wallpaper using a hook
provided in its configuration. Entities wanting to update the wallpaper should
call pacwall to ensure a single-source-of-truth for the wallpaper setting
process. 

=== On-startup programs
The window manager, `i3wm`, runs the "startup" programs because many display 
managers don't run the traditional x files. For example, `lightdm` doesn't run 
`.xinitrc`.

