#!/bin/bash
##########
# DESC:		Git will run this script prior to committing.
#				-Updates the lists of installed packages
# AUTHOR:   Silas Waxter (silaswaxter@gmail.com)
# DATE:		05/05/2022
##########

#####
# Definitions
#####
# Absolute path to this script,    (eg /home/silas/bin/foo.sh)
SCRIPT_NAME=$(readlink -f "$0")
# Absolute path this script is in, (eg /home/silas/bin)
SCRIPT_DIR=$(dirname "${SCRIPT_NAME}")

#Update pacman packages list
${SCRIPT_DIR}/../../installed_packages/fetch_installed_packages_list.sh
#Update foreign packages list (includes yay packages)
${SCRIPT_DIR}/../../installed_packages/fetch_installed_packages_list.sh -f
